language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: cRNQEyGKbBBVGrfehBJ50Yx87t53lgvHzeDomxPt4dTDv6a8MCNPyEBKbvdxyV24cKv9uI7NxQsrGTMMG9RskiJFfGTAuQoYWVDCa5vIQkdKA+2Dgq5IMitiKfdA1bGmekAcWuCu/U3463A0WwI9S2QsmvMc9OW/8R7IDKeP/gqR8nHwFdPyeDqCstI8FnCfnsPsV1CR0u28zZscd/UdYGEoFN+u5epct821W27GgvD6gTN59rfyigaddRpJOtAHKeZtK5Gc+d1lpAfoTFNwKx/eyVdD1egqzS0TDQTQFiWS4JvlEm2nbZxUsIPdIaTzYCy44V76LmMgkbaJnGWLTLnTtTgwNDssicyDtku/AaWH7141r47OgscnPOJpoTkiXeRa0QHE4gAU4ZQLGnE8wUy3ux3XIWm7GUqmCbyNzFJxgn9OkC0LJf/7vOY85wErfceRU8vUJV8QI0siXSqKXJEOQEvhEMUTHEBPgk1I2LX/YaYsE6TnCHoh9EokQ4rHeD9iP8PzI3D7hLHW53eUWyemB1iUez/t8KfQlE5py0Z/kfYj7ocG3xKLM501Apn2iIACbzvCeLZOD82UpXFEaS63ldQITrpgtgbbw1q/xnVuJ/h4jwIBstKJWP7pljdT5au6A6qlVPxrBZHPQC+CSq1fBxo06ZwWU9mH14Fnd8M=
  app: React-Hot-Cold
  on:
    repo: Taradacktl/React-Hot-Cold
