language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: GQjHTbZoOqNZn1xv5lGgiOAudnkosgdtc+P/TFWBklK746mellOvljftOkxvDGuG5MUef+h6Su+HSzuk2dC6+FRnzvan+ZYYCs/YFAlEdByZNf6QqX42Ot8GM6YCtizUgAOO7P2SreTo/PNUiaKJ9iiZPvnOznoTZC+uxGR6KW1sLwFNAZExGV7UaP0Gc9gYcUiaA1nE+NjhDcC/EpEpiczizXoQ3F8vvkFEVGzrur/Knt0yv+Mq0ISpeHrfyZSRX1bDIp8B50NvxVtWpC96XPGD1YBcOgLG5Vvbaphcu8L2RtD4OJWfFo9laeXwW8FgMio+4O7itswka+5yxoaLRdbSPlOjiXzg0GbKsRHVFQNffUkD/vc6qwfsG7kgn64eU2u8LR7deFgTVdTRs+YjB6wPXelX1sv9Pks2HkQ901Bf+d8Ab5iumU8qOkRrTte4hdqjjFw2QHi/4obI2DJmxv51M/wRLVbJWMuZt6jz4BRT2/ML/TOUTZbPebB1gYom19aC7Q87CT7XM2qoLPUkz9a5EEearVfQyaTWumb7/XmGcedVeiGXfK/bZ7pTQ4CMKpiv5YGAZrDkpWOv7nkph07wE/FdmG+yibboC7Idgaz+9lPkPRE4pKmvCJGj9Bph3cBj5eG8Pj01gfF9EWEDDlWtYTh00oWfEZTlyB5487U=
  app: React-Hot-Cold
  on:
    repo: Taradacktl/React-Hot-Cold
